export const popularSalons = [
  {
    id: 1,
    name: "Diamond SPA & Beauty",
    rating: 1,
    district: "Chilonzor",
    address: "Chilonzor tumani, Bunyodkor shoh ko'chasi, 11",
    title: "Premium SPA & Beauty",
    languages: ["O‘zbek", "Rus", "Ingliz"],
    image: "/images/salons/diamond-spa.jpg",
    description:
      "O‘zbekistonning eng mashhur SPA va kosmetologiya markazi. Zamonaviy muhit, xalqaro mutaxassislar va VIP xizmat.",
  },
  {
    id: 2,
    name: "Queen Beauty Studio",
    rating: 2,
    district: "Olmazor",
    address: "Olmazor tumani, G‘afur G‘ulom ko'chasi, 15",
    title: "Eng yaxshi stilistlar",
    languages: ["O‘zbek", "Rus"],
    image: "/images/salons/queen-beauty.jpg",
    description:
      "Stilistlar va koloristlar jamoasi, sertifikatli brend mahsulotlari, zamonaviy atmosfera.",
  },
  {
    id: 3,
    name: "Farhod Plaza Beauty",
    rating: 3,
    district: "Olmazor",
    address: "Olmazor tumani, Farhod bozori, 1-qavat",
    title: "Oila uchun qulay",
    languages: ["O‘zbek", "Rus"],
    image: "/images/salons/farhod-plaza.jpg",
    description:
      "Oilaviy xizmatlar, bolalar uchun zona, soch, tirnoq va yuz parvarishi.",
  },
  {
    id: 4,
    name: "Lux Beauty",
    rating: 4,
    district: "Yunusobod",
    address: "Yunusobod tumani, Bog'ishamol ko'chasi, 8",
    title: "Stil va komfort",
    languages: ["O‘zbek", "Rus", "Ingliz"],
    image: "/images/salons/lux-beauty.jpg",
    description:
      "Stil, soch kesish, makeup va spa. Hamma uchun ochiq, do‘stona muhit.",
  },
  {
    id: 5,
    name: "Aesthetic Island Spa",
    rating: 5,
    district: "Mirzo-Ulug‘bek",
    address: "Mirzo-Ulug‘bek tumani, Mustaqillik shoh ko'chasi, 6",
    title: "SPA va kosmetologiya",
    languages: ["O‘zbek", "Rus"],
    image: "/images/salons/aesthetic-island.jpg",
    description: "Massaj, spa va yuzni parvarishlashda yetakchi markaz.",
  },
  {
    id: 6,
    name: "Studio 026",
    rating: 6,
    district: "Mirzo-Ulug‘bek",
    address: "Mirzo-Ulug‘bek tumani, Zarafshan ko'chasi, 1",
    title: "Tajribali ustalar",
    languages: ["O‘zbek", "Rus", "Ingliz"],
    image: "/images/salons/studio026.jpg",
    description:
      "Yuqori darajada tirnoq va soch xizmati, eng so‘nggi tendensiyalar.",
  },
  {
    id: 7,
    name: "La Bellezza",
    rating: 7,
    district: "Olmazor",
    address: "Olmazor tumani, Farhod bozori, 1-qavat",
    title: "Italiya dizayni",
    languages: ["O‘zbek", "Rus"],
    image: "/images/salons/labellezza.jpg",
    description:
      "Evropa uslubi va sifatli xizmat, zamonaviy go‘zallik markazi.",
  },
  {
    id: 8,
    name: "Dream Look Studio",
    rating: 8,
    district: "Olmazor",
    address: "Olmazor tumani, Dadaxon Hasanov ko'chasi, 10",
    title: "Zamonaviy va qulay",
    languages: ["O‘zbek", "Rus", "Ingliz"],
    image: "/images/salons/dreamlook.jpg",
    description:
      "Innovatsion soch, manikyur va make-up. Professional stilistlar.",
  },
  {
    id: 9,
    name: "VIP Beauty",
    rating: 9,
    district: "Olmazor",
    address: "Olmazor tumani, Qatortol 35",
    title: "VIP xizmat",
    languages: ["O‘zbek", "Rus"],
    image: "/images/salons/vipbeauty.jpg",
    description: "Faol VIP mijozlar uchun maxfiy va sifatli xizmat.",
  },
  {
    id: 10,
    name: "Express Beauty",
    rating: 10,
    district: "Olmazor",
    address: "Olmazor tumani, G‘afur G‘ulom ko'chasi, 20",
    title: "Tezkor va sifatli",
    languages: ["O‘zbek", "Rus", "Ingliz"],
    image: "/images/salons/expressbeauty.jpg",
    description:
      "Qisqa vaqtda professional xizmat, har doim ochiq va qulay joylashuv.",
  },
];
